apiVersion: batch/v1
kind: Job
metadata:
  labels:
    name: sre-es-agg
  name: sre-es-agg
  namespace: openshift-logging
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: sre-es-agg
    spec:
      containers:
      - image: quay.io/chcollin/sre-es-ag
        imagePullPolicy: Always
        name: sre-es-agg
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/secret
          name: logging-elasticsearch
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: logging-elasticsearch
        secret:
          defaultMode: 420
          secretName: logging-elasticsearch

