apiVersion: batch/v1
kind: Job
metadata:
  labels:
    name: sre-es-agg
  name: sre-es-agg
  namespace: openshift-logging
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: sre-es-agg
    spec:
      containers:
      - image: elasticsearch-aggregator:latest
        imagePullPolicy: Always
        name: sre-es-agg
        volumeMounts:
        - mountPath: /app/secret
          name: logging-elasticsearch
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      volumes:
      - name: logging-elasticsearch
        secret:
          defaultMode: 420
          secretName: logging-elasticsearch
